'use client'

import Link from 'next/link'

export default function DisclaimerPage() {
  return (
    <div className="min-h-screen bg-background text-on-background">
      <header className="glass-nav border-b border-white/[0.05] px-6 py-4 flex items-center justify-between">
        <Link href="/" className="text-primary font-headline font-bold tracking-[0.2em] uppercase text-sm">ETHEREAL AI</Link>
        <Link href="/" className="text-on-surface-variant hover:text-primary transition-colors text-xs font-headline">← Back</Link>
      </header>
      <main className="max-w-2xl mx-auto px-6 py-12">
        <h1 className="text-3xl font-headline font-bold gradient-text mb-8">Disclaimer</h1>
        <div className="space-y-6 font-body text-on-surface-variant leading-relaxed text-sm">

          <section className="glass-card rounded-xl p-5 border-l-4 border-primary/50">
            <h2 className="font-headline font-bold text-on-surface text-lg mb-3">⚠️ Important Investment Disclaimer</h2>
            <p className="font-semibold text-on-surface">
              Ethereal AI does NOT provide investment advice, financial advice, trading advice, or any other form of professional financial guidance. 
              All content, analysis, and AI-generated reports on this platform are for <strong>informational and educational purposes only</strong>.
            </p>
          </section>

          <section>
            <h2 className="font-headline font-bold text-on-surface text-lg mb-3">1. Not Financial Advice</h2>
            <p>
              The AI-powered stock analysis, sentiment indicators, market data, and any other information provided by Ethereal AI should not be interpreted as:
            </p>
            <ul className="list-disc list-inside mt-2 space-y-1 pl-2">
              <li>A recommendation to buy, sell, or hold any security or financial instrument</li>
              <li>Investment advice or financial planning guidance</li>
              <li>An offer or solicitation to purchase or sell securities</li>
              <li>A guarantee of future performance or investment returns</li>
              <li>A substitute for professional financial advice from a licensed advisor</li>
            </ul>
          </section>

          <section>
            <h2 className="font-headline font-bold text-on-surface text-lg mb-3">2. AI-Generated Content Limitations</h2>
            <p>
              Our AI analysis is generated by algorithmic models based on publicly available market data. These models have inherent limitations:
            </p>
            <ul className="list-disc list-inside mt-2 space-y-1 pl-2">
              <li>AI analysis may be inaccurate, incomplete, or outdated</li>
              <li>Sentiment indicators and trend labels are algorithmic estimates, not definitive assessments</li>
              <li>Past market patterns do not predict future performance</li>
              <li>AI models cannot account for unforeseen market events, regulatory changes, or black swan events</li>
              <li>Any references to &quot;accuracy&quot; or &quot;performance&quot; metrics refer to historical backtesting only and do not guarantee future results</li>
            </ul>
          </section>

          <section>
            <h2 className="font-headline font-bold text-on-surface text-lg mb-3">3. Risk Disclosure</h2>
            <p>
              Investing in securities involves substantial risk of loss and is not suitable for every investor. The value of securities may fluctuate, and as a result, you may lose more than your original investment. You should be aware of the following risks:
            </p>
            <ul className="list-disc list-inside mt-2 space-y-1 pl-2">
              <li>Market risk: Securities prices can decline significantly</li>
              <li>Liquidity risk: You may not be able to sell securities at a desired price or time</li>
              <li>Volatility risk: Markets can experience sudden and extreme price movements</li>
              <li>Systemic risk: Broad market downturns can affect virtually all securities</li>
            </ul>
          </section>

          <section>
            <h2 className="font-headline font-bold text-on-surface text-lg mb-3">4. No Guarantee of Results</h2>
            <p>
              Ethereal AI makes no representations or warranties regarding the accuracy, reliability, completeness, or timeliness of any analysis, data, or information provided on this platform. We explicitly disclaim any guarantee of:
            </p>
            <ul className="list-disc list-inside mt-2 space-y-1 pl-2">
              <li>Investment profits or returns</li>
              <li>Accuracy of AI-generated predictions or analysis</li>
              <li>Reliability of market data or sentiment indicators</li>
              <li>Suitability of any analysis for your specific financial situation</li>
            </ul>
          </section>

          <section>
            <h2 className="font-headline font-bold text-on-surface text-lg mb-3">5. Consult a Professional</h2>
            <p>
              Before making any investment decisions, you should consult with a qualified, licensed financial advisor who can assess your individual financial situation, risk tolerance, and investment objectives. Never make investment decisions based solely on AI-generated analysis or information found on this platform.
            </p>
          </section>

          <section>
            <h2 className="font-headline font-bold text-on-surface text-lg mb-3">6. Third-Party Data</h2>
            <p>
              Market data, stock prices, and financial metrics displayed on this platform are sourced from third-party data providers and may be delayed. Ethereal AI is not responsible for errors, omissions, or delays in third-party data. Always verify critical financial data through official sources before making investment decisions.
            </p>
          </section>

          <section>
            <h2 className="font-headline font-bold text-on-surface text-lg mb-3">7. Limitation of Liability</h2>
            <p>
              To the maximum extent permitted by law, Ethereal AI and its operators shall not be liable for any direct, indirect, incidental, special, consequential, or punitive damages arising from your use of or reliance on any information, analysis, or services provided on this platform, even if advised of the possibility of such damages.
            </p>
          </section>

          <section className="glass-card rounded-xl p-5 border-l-4 border-secondary/50">
            <h2 className="font-headline font-bold text-on-surface text-lg mb-3">Key Takeaway</h2>
            <p className="font-semibold text-on-surface">
              Ethereal AI is an informational tool, not a financial advisor. All analysis is algorithmically generated and should be used as one of many inputs in your research process — never as the sole basis for investment decisions.
            </p>
          </section>

          <p className="text-xs text-on-surface-variant/60 pt-8">Last updated: April 2026</p>
        </div>
      </main>
    </div>
  )
}
