import type { Config } from 'tailwindcss'

const config: Config = {
  darkMode: 'class',
  content: [
    './src/pages/**/*.{js,ts,jsx,tsx,mdx}',
    './src/components/**/*.{js,ts,jsx,tsx,mdx}',
    './src/app/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  theme: {
    extend: {
      colors: {
        // The Predictive Prism — Stitch Design System (AI Stock Diagnoser)
        'background': '#0a0f13',
        'on-background': '#f3f7fd',
        'surface': '#0a0f13',
        'surface-dim': '#0a0f13',
        'surface-bright': '#252d33',
        'surface-container': '#141a1f',
        'surface-container-high': '#1a2026',
        'surface-container-highest': '#1f272c',
        'surface-container-low': '#0e1418',
        'surface-container-lowest': '#000000',
        'surface-variant': '#1f272c',
        'surface-tint': '#81ecff',
        'on-surface': '#f3f7fd',
        'on-surface-variant': '#a7abb1',
        'inverse-surface': '#f6faff',
        'inverse-on-surface': '#51565a',
        'inverse-primary': '#006976',
        'primary': '#81ecff',
        'primary-dim': '#00d4ec',
        'primary-container': '#00e3fd',
        'on-primary': '#005762',
        'on-primary-container': '#004d57',
        'on-primary-fixed': '#003840',
        'on-primary-fixed-variant': '#005762',
        'primary-fixed': '#00e3fd',
        'primary-fixed-dim': '#00d4ec',
        'secondary': '#5cfd80',
        'secondary-dim': '#4bee74',
        'secondary-container': '#006e2a',
        'on-secondary': '#005d22',
        'on-secondary-container': '#e4ffe1',
        'on-secondary-fixed': '#004819',
        'on-secondary-fixed-variant': '#006827',
        'secondary-fixed': '#5cfd80',
        'secondary-fixed-dim': '#4bee74',
        'tertiary': '#a68cff',
        'tertiary-dim': '#7e51ff',
        'tertiary-container': '#7c4dff',
        'on-tertiary': '#25006b',
        'on-tertiary-container': '#ffffff',
        'on-tertiary-fixed': '#1c0055',
        'on-tertiary-fixed-variant': '#4000ad',
        'tertiary-fixed': '#b8a3ff',
        'tertiary-fixed-dim': '#ab93ff',
        'error': '#ff716c',
        'error-dim': '#d7383b',
        'error-container': '#9f0519',
        'on-error': '#490006',
        'on-error-container': '#ffa8a3',
        'outline': '#71767b',
        'outline-variant': '#43484d',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        sm: '0.125rem',
        lg: '0.5rem',
        xl: '0.75rem',
        '2xl': '1rem',
        '3xl': '1.5rem',
        '4xl': '2rem',
        full: '9999px',
      },
      fontFamily: {
        headline: ['Space Grotesk', 'sans-serif'],
        body: ['Inter', 'sans-serif'],
        label: ['Inter', 'sans-serif'],
      },
      animation: {
        'marquee': 'marquee 40s linear infinite',
        'loading-bar': 'loadingProgress 1.5s ease-in-out forwards',
        'glow-pulse': 'glow-pulse 2s cubic-bezier(0.4, 0, 0.6, 1) infinite',
        'ripple': 'ripple 1.5s linear infinite',
        'btn-activate': 'btn-activate 0.6s cubic-bezier(0.34, 1.56, 0.64, 1) forwards',
        'progress': 'progress 2s ease-in-out forwards',
        'scroll-vertical': 'scroll-vertical 30s linear infinite',
        'float-symbol': 'float-symbol 4s ease-in-out infinite',
        'hot-stocks-scroll': 'hot-stocks-scroll 60s linear infinite',
        'pulse-ring': 'pulse-ring 2s cubic-bezier(0.4, 0, 0.6, 1) infinite',
        'scan-line': 'scan-line 2s linear infinite',
      },
      keyframes: {
        'marquee': {
          '0%': { transform: 'translateX(0)' },
          '100%': { transform: 'translateX(-50%)' },
        },
        'loadingProgress': {
          '0%': { width: '0%' },
          '100%': { width: '100%' },
        },
        'glow-pulse': {
          '0%, 100%': { boxShadow: '0 0 5px #81ecff, 0 0 10px #81ecff' },
          '50%': { boxShadow: '0 0 20px #81ecff, 0 0 30px #81ecff' },
        },
        'ripple': {
          '0%': { transform: 'scale(0.8)', opacity: '0.5' },
          '100%': { transform: 'scale(2.5)', opacity: '0' },
        },
        'btn-activate': {
          '0%': { opacity: '0.3', transform: 'scale(0.98)' },
          '100%': { opacity: '1', transform: 'scale(1)' },
        },
        'scroll-vertical': {
          '0%': { transform: 'translateY(0)' },
          '100%': { transform: 'translateY(-50%)' },
        },
        'progress': {
          '0%': { width: '0%' },
          '100%': { width: '100%' },
        },
        'float-symbol': {
          '0%, 100%': { transform: 'translateY(0) scale(1)', opacity: '0' },
          '50%': { transform: 'translateY(-40px) scale(1.1)', opacity: '0.6' },
        },
        'hot-stocks-scroll': {
          '0%': { transform: 'translateY(0)' },
          '100%': { transform: 'translateY(-33.33%)' },
        },
        'pulse-ring': {
          '0%': { transform: 'scale(0.95)', opacity: '0.7' },
          '50%': { transform: 'scale(1.3)', opacity: '0' },
          '100%': { transform: 'scale(0.95)', opacity: '0' },
        },
        'scan-line': {
          '0%': { transform: 'translateY(-100%)' },
          '100%': { transform: 'translateY(400px)' },
        },
      },
    },
  },
  plugins: [],
}
export default config
