import type { Config } from 'tailwindcss'

const config: Config = {
  darkMode: 'class',
  content: [
    './src/pages/**/*.{js,ts,jsx,tsx,mdx}',
    './src/components/**/*.{js,ts,jsx,tsx,mdx}',
    './src/app/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  theme: {
    extend: {
      colors: {
        // Luminescent Ledger — Stitch huihui2 Design System
        'background': '#0b0e14',
        'on-background': '#ecedf6',
        'surface': '#0b0e14',
        'surface-dim': '#0b0e14',
        'surface-bright': '#282c36',
        'surface-container': '#161a21',
        'surface-container-high': '#1c2028',
        'surface-container-highest': '#22262f',
        'surface-container-low': '#10131a',
        'surface-container-lowest': '#000000',
        'surface-variant': '#22262f',
        'surface-tint': '#a3a6ff',
        'on-surface': '#ecedf6',
        'on-surface-variant': '#a9abb3',
        'inverse-surface': '#f9f9ff',
        'inverse-on-surface': '#52555c',
        'inverse-primary': '#494bd7',
        'primary': '#a3a6ff',
        'primary-dim': '#6063ee',
        'primary-container': '#9396ff',
        'primary-fixed': '#9396ff',
        'primary-fixed-dim': '#8387ff',
        'on-primary': '#0f00a4',
        'on-primary-container': '#0a0081',
        'on-primary-fixed': '#000000',
        'on-primary-fixed-variant': '#0e009d',
        'secondary': '#c180ff',
        'secondary-dim': '#9c48ea',
        'secondary-container': '#6f00be',
        'secondary-fixed': '#e5c6ff',
        'secondary-fixed-dim': '#dbb4ff',
        'on-secondary': '#33005b',
        'on-secondary-container': '#e9cdff',
        'on-secondary-fixed': '#4f0089',
        'on-secondary-fixed-variant': '#7511c3',
        'tertiary': '#ffa5d9',
        'tertiary-dim': '#ef81c4',
        'tertiary-container': '#ff8ed2',
        'tertiary-fixed': '#ff8ed2',
        'tertiary-fixed-dim': '#ef81c4',
        'on-tertiary': '#701455',
        'on-tertiary-container': '#63054a',
        'on-tertiary-fixed': '#3b002b',
        'on-tertiary-fixed-variant': '#6e1354',
        'error': '#ff6e84',
        'error-dim': '#d73357',
        'error-container': '#a70138',
        'on-error': '#490013',
        'on-error-container': '#ffb2b9',
        'outline': '#73757d',
        'outline-variant': '#45484f',
      },
      borderRadius: {
        DEFAULT: '0.125rem',
        sm: '0.0625rem',
        lg: '0.25rem',
        xl: '0.5rem',
        '2xl': '0.75rem',
        '3xl': '1rem',
        '4xl': '1.5rem',
        full: '9999px',
      },
      fontFamily: {
        headline: ['Inter', 'sans-serif'],
        body: ['Inter', 'sans-serif'],
        label: ['Inter', 'sans-serif'],
      },
      animation: {
        'pulse-glow': 'pulse-glow 3s cubic-bezier(0.4, 0, 0.6, 1) infinite',
        'pop-in': 'pop-in 0.6s cubic-bezier(0.34, 1.56, 0.64, 1) forwards',
      },
      keyframes: {
        'pulse-glow': {
          '0%, 100%': { opacity: '1', filter: 'brightness(1)' },
          '50%': { opacity: '0.8', filter: 'brightness(1.2)' },
        },
        'pop-in': {
          '0%': { opacity: '0.3', transform: 'scale(0.98)' },
          '100%': { opacity: '1', transform: 'scale(1)' },
        },
      },
    },
  },
  plugins: [],
}
export default config
