import type { Config } from 'tailwindcss'

const config: Config = {
  darkMode: 'class',
  content: [
    './src/pages/**/*.{js,ts,jsx,tsx,mdx}',
    './src/components/**/*.{js,ts,jsx,tsx,mdx}',
    './src/app/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  theme: {
    extend: {
      colors: {
        // The Obsidian Ledger — Stitch Design System
        'background': '#0e0e0f',
        'on-background': '#ffffff',
        'surface': '#0e0e0f',
        'surface-dim': '#0e0e0f',
        'surface-bright': '#2c2c2d',
        'surface-container': '#1a191b',
        'surface-container-high': '#201f21',
        'surface-container-highest': '#262627',
        'surface-container-low': '#131314',
        'surface-container-lowest': '#000000',
        'surface-variant': '#262627',
        'surface-tint': '#a1faff',
        'on-surface': '#ffffff',
        'on-surface-variant': '#adaaab',
        'inverse-surface': '#fcf8f9',
        'inverse-on-surface': '#565556',
        'inverse-primary': '#006a6e',
        'primary': '#a1faff',
        'primary-dim': '#00e5ee',
        'primary-container': '#00f4fe',
        'on-primary': '#006165',
        'on-primary-container': '#00575b',
        'on-primary-fixed': '#004346',
        'on-primary-fixed-variant': '#006266',
        'primary-fixed': '#00f4fe',
        'primary-fixed-dim': '#00e5ee',
        'secondary': '#c3f400',
        'secondary-dim': '#b7e500',
        'secondary-container': '#506600',
        'on-secondary': '#455900',
        'on-secondary-container': '#efffbc',
        'on-secondary-fixed': '#354500',
        'on-secondary-fixed-variant': '#4e6300',
        'secondary-fixed': '#c3f400',
        'secondary-fixed-dim': '#b7e500',
        'tertiary': '#9cff93',
        'tertiary-dim': '#00ec3b',
        'tertiary-container': '#00fc40',
        'on-tertiary': '#006413',
        'on-tertiary-container': '#005a10',
        'on-tertiary-fixed': '#00440a',
        'on-tertiary-fixed-variant': '#006513',
        'tertiary-fixed': '#00fc40',
        'tertiary-fixed-dim': '#00ec3b',
        'error': '#ff716c',
        'error-dim': '#d7383b',
        'error-container': '#9f0519',
        'on-error': '#490006',
        'on-error-container': '#ffa8a3',
        'outline': '#767576',
        'outline-variant': '#484849',
      },
      borderRadius: {
        DEFAULT: '0.125rem',
        sm: '0.0625rem',
        lg: '0.25rem',
        xl: '0.5rem',
        '2xl': '1rem',
        '3xl': '1.5rem',
        '4xl': '2rem',
        full: '0.75rem',
      },
      fontFamily: {
        headline: ['Space Grotesk', 'sans-serif'],
        body: ['Inter', 'sans-serif'],
        label: ['Space Grotesk', 'sans-serif'],
      },
      animation: {
        'marquee': 'marquee 40s linear infinite',
        'loading-bar': 'loadingProgress 1.5s ease-in-out forwards',
        'glow-pulse': 'glow-pulse 2s cubic-bezier(0.4, 0, 0.6, 1) infinite',
        'ripple': 'ripple 1.5s linear infinite',
        'btn-activate': 'btn-activate 0.6s cubic-bezier(0.34, 1.56, 0.64, 1) forwards',
        'progress': 'progress 2s ease-in-out forwards',
        'scroll-vertical': 'scroll-vertical 30s linear infinite',
        'float-symbol': 'float-symbol 4s ease-in-out infinite',
        'hot-stocks-scroll': 'hot-stocks-scroll 60s linear infinite',
        'pulse-ring': 'pulse-ring 2s cubic-bezier(0.4, 0, 0.6, 1) infinite',
      },
      keyframes: {
        'marquee': {
          '0%': { transform: 'translateX(0)' },
          '100%': { transform: 'translateX(-50%)' },
        },
        'loadingProgress': {
          '0%': { width: '0%' },
          '100%': { width: '100%' },
        },
        'glow-pulse': {
          '0%, 100%': { boxShadow: '0 0 5px #a1faff, 0 0 10px #a1faff' },
          '50%': { boxShadow: '0 0 20px #a1faff, 0 0 30px #a1faff' },
        },
        'ripple': {
          '0%': { transform: 'scale(0.8)', opacity: '0.5' },
          '100%': { transform: 'scale(2.5)', opacity: '0' },
        },
        'btn-activate': {
          '0%': { opacity: '0.3', transform: 'scale(0.98)' },
          '100%': { opacity: '1', transform: 'scale(1)' },
        },
        'scroll-vertical': {
          '0%': { transform: 'translateY(0)' },
          '100%': { transform: 'translateY(-50%)' },
        },
        'progress': {
          '0%': { width: '0%' },
          '100%': { width: '100%' },
        },
        'float-symbol': {
          '0%, 100%': { transform: 'translateY(0) scale(1)', opacity: '0' },
          '50%': { transform: 'translateY(-40px) scale(1.1)', opacity: '0.6' },
        },
        'hot-stocks-scroll': {
          '0%': { transform: 'translateY(0)' },
          '100%': { transform: 'translateY(-33.33%)' },
        },
        'pulse-ring': {
          '0%': { transform: 'scale(0.95)', opacity: '0.7' },
          '50%': { transform: 'scale(1.3)', opacity: '0' },
          '100%': { transform: 'scale(0.95)', opacity: '0' },
        },
      },
    },
  },
  plugins: [],
}
export default config
