'use client'

import Link from 'next/link'

export default function TermsPage() {
  return (
    <div className="min-h-screen bg-white text-slate-800">
      <header className="sticky top-0 z-50 bg-white/90 backdrop-blur-md border-b border-slate-100 py-4 px-4 sm:px-6 flex items-center justify-between">
        <div className="font-bold text-xl tracking-tight">AI Stock Diagnosis</div>
        <Link href="/" className="text-brand text-sm font-medium hover:text-brand-dark transition-colors">← Back</Link>
      </header>
      <main className="max-w-2xl mx-auto px-6 py-12">
        <h1 className="text-3xl font-extrabold text-slate-900 mb-8">Terms of Service</h1>
        <div className="space-y-6 text-slate-600 leading-relaxed text-sm">
          <section>
            <h2 className="font-bold text-slate-900 text-lg mb-3">1. Acceptance of Terms</h2>
            <p>By accessing and using AI Stock Diagnosis, you agree to be bound by these Terms of Service. If you do not agree with any part of these terms, you must discontinue use of the platform immediately.</p>
          </section>
          <section>
            <h2 className="font-bold text-slate-900 text-lg mb-3">2. Service Description</h2>
            <p>AI Stock Diagnosis provides AI-powered stock analysis tools and educational content delivered via WhatsApp. Our services generate analysis based on algorithmic models and publicly available market data.</p>
          </section>
          <section>
            <h2 className="font-bold text-slate-900 text-lg mb-3">3. Disclaimer</h2>
            <p>All AI-generated analysis is for informational purposes only and does not constitute financial advice, investment recommendations, or solicitation to buy or sell securities. Past performance and AI predictions do not guarantee future results.</p>
          </section>
          <section>
            <h2 className="font-bold text-slate-900 text-lg mb-3">4. User Responsibility</h2>
            <p>You are solely responsible for your investment decisions. You should consult with a qualified financial advisor before making any investment decisions. AI Stock Diagnosis shall not be liable for any financial losses resulting from actions taken based on our analysis.</p>
          </section>
          <section>
            <h2 className="font-bold text-slate-900 text-lg mb-3">5. Intellectual Property</h2>
            <p>All content, algorithms, and analysis generated by AI Stock Diagnosis are the intellectual property of the platform. You may not reproduce, distribute, or create derivative works without explicit written permission.</p>
          </section>
          <section>
            <h2 className="font-bold text-slate-900 text-lg mb-3">6. Limitation of Liability</h2>
            <p>AI Stock Diagnosis provides services on an &quot;as is&quot; basis. We make no warranties regarding accuracy, completeness, or timeliness of analysis. Our total liability shall not exceed the amount paid by you for the service.</p>
          </section>
          <p className="text-xs text-slate-400 pt-8">Last updated: April 2026</p>
        </div>
      </main>
    </div>
  )
}
