'use client'
import Link from 'next/link'
export default function TermsPage() {
  return (
    <div className="min-h-screen bg-background text-on-background">
      <header className="bg-neutral-950 text-lime-400 sticky top-0 z-50 border-b border-white/10 flex justify-between items-center w-full px-5 py-4">
        <div className="flex items-center gap-3">
          <div className="w-8 h-8 rounded-full bg-surface-container overflow-hidden flex items-center justify-center">
            <span className="material-symbols-outlined text-primary-container text-lg">smart_toy</span>
          </div>
          <span className="text-2xl font-black italic text-primary-container tracking-tighter">StockAI</span>
        </div>
        <Link href="/" className="text-on-surface-variant text-label-md font-medium hover:text-primary-container transition-colors">← Back</Link>
      </header>
      <main className="max-w-2xl mx-auto px-6 py-12">
        <h1 className="text-headline-lg font-bold text-on-surface mb-8">Terms of Service</h1>
        <div className="space-y-6 text-on-surface-variant leading-relaxed text-body-md">
          <section><h2 className="font-semibold text-on-surface text-headline-md mb-3">1. Acceptance of Terms</h2><p>By accessing and using StockAI, you agree to be bound by these Terms of Service. If you do not agree, discontinue use immediately.</p></section>
          <section><h2 className="font-semibold text-on-surface text-headline-md mb-3">2. Service Description</h2><p>StockAI provides AI-powered stock analysis tools. Our services generate analysis based on algorithmic models and publicly available market data.</p></section>
          <section><h2 className="font-semibold text-on-surface text-headline-md mb-3">3. Disclaimer</h2><p>All AI-generated analysis is for informational purposes only and does not constitute financial advice, investment recommendations, or solicitation to buy or sell securities.</p></section>
          <section><h2 className="font-semibold text-on-surface text-headline-md mb-3">4. User Responsibility</h2><p>You are solely responsible for your investment decisions. You should consult with a qualified financial advisor before making any investment decisions.</p></section>
          <section><h2 className="font-semibold text-on-surface text-headline-md mb-3">5. Intellectual Property</h2><p>All content, algorithms, and analysis generated by StockAI are the intellectual property of the platform. You may not reproduce, distribute, or create derivative works without permission.</p></section>
          <section><h2 className="font-semibold text-on-surface text-headline-md mb-3">6. Limitation of Liability</h2><p>StockAI provides services on an &quot;as is&quot; basis. We make no warranties regarding accuracy, completeness, or timeliness of analysis.</p></section>
          <p className="text-xs text-on-surface-variant/60 pt-8">Last updated: April 2026</p>
        </div>
      </main>
    </div>
  )
}
