'use client'

import Link from 'next/link'

export default function TermsPage() {
  return (
    <div className="min-h-screen bg-background text-on-background">
      <header className="bg-background/80 backdrop-blur-xl sticky top-0 z-50 shadow-sm border-b border-outline-variant/10 px-6 py-3 max-w-7xl mx-auto">
        <div className="flex items-center justify-between">
          <Link href="/" className="text-primary font-headline font-black tracking-tighter text-xl">SOVEREIGN</Link>
          <Link href="/" className="text-on-surface-variant hover:text-primary transition-colors text-xs">← Back</Link>
        </div>
      </header>
      <main className="max-w-3xl mx-auto px-6 py-12">
        <h1 className="text-3xl font-headline font-bold text-primary mb-8">Terms of Service</h1>
        <div className="space-y-6 font-body text-on-surface-variant leading-relaxed text-sm">
          <section>
            <h2 className="font-headline font-bold text-on-surface text-lg mb-3">1. Acceptance of Terms</h2>
            <p>By accessing and using this AI Stock Diagnosis platform, you agree to be bound by these Terms of Service. If you do not agree with any part of these terms, you must discontinue use of the platform immediately.</p>
          </section>
          <section>
            <h2 className="font-headline font-bold text-on-surface text-lg mb-3">2. Service Description</h2>
            <p>This platform provides AI-powered stock diagnosis and quantitative analysis tools. Our services generate predictions and risk assessments based on algorithmic models and publicly available market data.</p>
          </section>
          <section>
            <h2 className="font-headline font-bold text-on-surface text-lg mb-3">3. Disclaimer</h2>
            <p>All AI-generated analysis is for informational purposes only and does not constitute financial advice, investment recommendations, or solicitation to buy or sell securities. Past performance and AI predictions do not guarantee future results.</p>
          </section>
          <section>
            <h2 className="font-headline font-bold text-on-surface text-lg mb-3">4. User Responsibility</h2>
            <p>You are solely responsible for your investment decisions. You should consult with a qualified financial advisor before making any investment decisions. This platform shall not be liable for any financial losses resulting from actions taken based on our analysis.</p>
          </section>
          <section>
            <h2 className="font-headline font-bold text-on-surface text-lg mb-3">5. Intellectual Property</h2>
            <p>All content, algorithms, and analysis generated by this platform are the intellectual property of the service. You may not reproduce, distribute, or create derivative works without explicit written permission.</p>
          </section>
          <section>
            <h2 className="font-headline font-bold text-on-surface text-lg mb-3">6. Limitation of Liability</h2>
            <p>This platform provides services on an &quot;as is&quot; basis. We make no warranties regarding accuracy, completeness, or timeliness of analysis. Our total liability shall not exceed the amount paid by you for the service.</p>
          </section>
          <p className="text-xs text-on-surface-variant/60 pt-8">Last updated: April 2026</p>
        </div>
      </main>
    </div>
  )
}
